config/routes.rb
TickitApp::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users
  resources :users, :only => :show do
    resources :tickits
  end
  
  match 'home' => 'home#show'

end

app/models/tickit.rb
class Tickit
  include Mongoid::Document
  include Mongoid::Timestamps 
  field :title, :type => String
  field :description, :type => String
  field :prompt, :type => String
  field :created_at, :type => Date
  field :created_by, :type => String
  field :updated_at, :type => Date
  field :updated_by, :type => String
  
  validates_presence_of :title, :description, :prompt
  embeds_many :tickit_fields
  
  accepts_nested_attributes_for :tickit_fields
    
  referenced_in :user
end

app/models/tickit_field.rb
class TickitField
  include Mongoid::Document
  include Mongoid::Timestamps 
  field :prompt, :type => String
  
  embedded_in :tickit, :inverse_of => :tickit_fields
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps 
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :rememberable
         
  references_many :tickits
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
  end

end

app/controllers/tickits_controller.rb
class TickitsController < ApplicationController
  respond_to :html, :xml, :json
  layout "home"
  
  def index
    @user = User.find(params[:user_id])
    @tickits = @user.tickits
    respond_with(@user,@tickits)
  end

  def show
    @user = User.find(params[:user_id])
    @tickit = @user.tickits.find(params[:id])
    respond_with(@user, @tickit)
  end

  def new
    @user = User.find(params[:user_id])
    @tickit = Tickit.new
    respond_with(@user, @tickit)
  end

  def edit
    @user = User.find(params[:user_id])
    @tickit = @user.tickits.find(params[:id])
  end

  def create
    sleep(3)
    @user = User.find(params[:user_id])
    @tickit = @user.tickits.create(params[:tickit])
    respond_to do |format|
      if @tickit.save
        format.html { redirect_to(@user, :notice => 'Tickit was successfully created.') }
        format.xml  { render :xml => @tickit, :status => :created, :location => @tickit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tickit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tickits/1
  # PUT /tickits/1.xml
  def update
    @user = User.find(params[:user_id])
    @tickit = @user.tickits.find(params[:id])
    @tickit.updated_at = DateTime.now
    respond_to do |format|
      if @tickit.update_attributes(params[:tickit])
        format.html { redirect_to(@user, :notice => 'Tickit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tickit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tickits/1
  # DELETE /tickits/1.xml
  def destroy
    @user = User.find(params[:user_id])
    @tickit = @user.tickits.find(params[:id])
    @tickit.destroy

    respond_to do |format|
      format.html { redirect_to(user_url(@user)) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  layout "home"
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_dt(datetime)
    datetime.strftime("%m/%d/%Y")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickits_helper.rb
module TickitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.haml
#container
  %p 
    User:
    = @user.email

  %table
    %tr
      %th Title
      %th Description
      %th
    - @user.tickits.each do |tickit|
      %tr
        %td= link_to tickit.title, edit_user_tickit_path(@user, tickit)      
        %td= tickit.description
        %td= link_to 'Destroy', user_tickit_path(@user, tickit), :confirm => 'Are you sure?', :method => :delete
  %br/
  = link_to 'New Tickit sheet', new_user_tickit_path(@user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tickit
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Tickit
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #header
      #logo-area
        Ticket
      #title-area
        count. learn. share.
      #action-area
        %ul.hmenu
          = render 'devise/menu/registration_items'
          = render 'devise/menu/login_items'
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/tickits/_form.html.haml
= form_for [@user, @tickit] do |f|
  - if @tickit.errors.any?
    #error_explanation
      %h2
        = pluralize(@tickit.errors.count, "error")
        prohibited this tickit from being saved:
      %ul
        - @tickit.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    = f.text_field :title, :class => "input-area"
  .field
    = f.label :description
    = f.text_area :description, :class => "input-area"
  .field
    = f.label :prompt
    = f.text_field :prompt, :class => "input-area"
  = f.fields_for :tickit_fields do |tf_fields|
    = tf_fields.label :prompt
    = tf_fields.text_field :prompt, :class => "input-area"
  .actions
    = f.submit :disable_with => "Please Wait..."

app/views/tickits/edit.html.haml
%h1 Editing tickit
= render 'form'
= link_to 'Back', user_path(@user)

app/views/tickits/index.html.haml
%h1 Listing tickits
%table
  %tr
    %th Title
    %th Description
    %th Created
    %th
    %th
    %th
  - @tickits.each do |tickit|
    %tr
      %td= tickit.title
      %td= tickit.description
      %td= format_dt(tickit.created_at)
      %td= link_to 'Show', tickit
      %td= link_to 'Edit', edit_tickit_path(tickit)
      %td= link_to 'Destroy', tickit, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Tickit sheet', new_user_tickit_path(@user)

app/views/tickits/new.html.haml
%h1 New tickit
= render 'form'
= link_to 'Back', user_tickits_path(@user)

app/views/tickits/show.html.haml
%p#notice= notice
%h2= @tickit.title
%p= @tickit.description
%h3= @tickit.prompt
= link_to 'Edit', edit_user_tickit_path(@user, @tickit)

= link_to 'Back', user_tickits_path(@user)

app/views/users/index.html.haml
#container
  %h1 Home#index
  - @users.each do |user|
    %p 
      User
      =link_to user.email, user

app/views/users/show.html.haml
#container
  %p 
    User:
    = @user.email

  %table
    %tr
      %th Title
      %th Description
      %th
    - @user.tickits.each do |tickit|
      %tr
        %td= link_to tickit.title, edit_user_tickit_path(@user, tickit)      
        %td= tickit.description
        %td= link_to 'Destroy', user_tickit_path(@user, tickit), :confirm => 'Are you sure?', :method => :delete
  %br/
  = link_to 'New Tickit sheet', new_user_tickit_path(@user)  